sudo: required
jdk:
  - oraclejdk8
install: true
script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version
language: java
script: mvn clean package
deploy:
  provider: releases
  api_key:
    secure: tnm/ghPDQI1UZsIdbjSA92LrDMkvuweZ2BXomHIF9mWwaJgFpJAHXeQP2M16dTagM0RKbnMQMrjBB3d1NSFY7Ub5jQI8Qitzs7U8hmIN7DnpCq1eJHKVPijNwRbwoXBhMqnO0XoEekSR3i4JDyG1livny0pGvS/fG5LXcMfYFqo=
  file: target/releases/elasticsearch-analysis-stconvert-*.zip
  file_glob: true
  on:
    repo: medcl/elasticsearch-analysis-stconvert
    tags: true
    all_branches: true

